export const DOGSBYTEMPERAMENT = "DOGSBYTEMPERAMENT";
export const WEIGHT = "WEIGHT"
export const ALPHABETIC = "ALPHABETIC"
export const GET_ALL = "GET_ALL"
export const GET_ALL_TEMPS = "GET_ALL_TEMPS"
export const FILTER_ORIGIN = "FILTER_ORIGIN"
